# This workflow updates runs main.py and eventually posts updates on Twitter

name: Runner

on:
  schedule:
   - cron: "*/1 * * * *" # Runs every 10 minutes, everyday (actual timing may vary, depending on GitHub)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo content # Checkout the repository content to GitHub runner
      uses: actions/checkout@v2
    - name: setup python # Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 # The script actually runs fine with Python 3.8
    - name: install pip # Install pip
      run: |
        python -m pip install --upgrade pip
    - name: tweepy
      run: |
        python -m pip install tweepy==3.8.0
    - name: install requirements # Install external modules
      run: |
        pip3 install -r requirements.txt
    - name: execute py script # Run the script to fetch the latest data
      run: |
        python main.py
